CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS character_sheets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  character_name VARCHAR(80) NOT NULL,
  occupation VARCHAR(80) NULL,
  age TINYINT UNSIGNED NULL,
  residence VARCHAR(120) NULL,
  birthplace VARCHAR(120) NULL,
  str_val TINYINT UNSIGNED NOT NULL,
  con_val TINYINT UNSIGNED NOT NULL,
  dex_val TINYINT UNSIGNED NOT NULL,
  app_val TINYINT UNSIGNED NOT NULL,
  pow_val TINYINT UNSIGNED NOT NULL,
  int_val TINYINT UNSIGNED NOT NULL,
  siz_val TINYINT UNSIGNED NOT NULL,
  edu_val TINYINT UNSIGNED NOT NULL,
  hp TINYINT UNSIGNED NULL,
  max_hp TINYINT UNSIGNED NULL,
  sanity TINYINT UNSIGNED NULL,
  max_sanity TINYINT UNSIGNED NULL,
  magic_points TINYINT UNSIGNED NULL,
  max_magic_points TINYINT UNSIGNED NULL,
  move_rate TINYINT UNSIGNED NULL,
  damage_bonus VARCHAR(20) NULL,
  build VARCHAR(20) NULL,
  skills_json TEXT NULL,
  equipment_text TEXT NULL,
  notes_text TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sheets_user (user_id),
  CONSTRAINT fk_sheets_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO users VALUES (1, 'testuser', '$2y$10$fw6JK6qtuRU6wxsaiCewJeCt9csQ8C2g6Msfv/QPAH2kDzyeURmoy');


